modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/CraftTweaker/ContentTweaker/issues"
license="MIT"
[[mods]]
modId="contenttweaker"
version="${file.jarVersion}"
displayName="ContentTweaker"
displayURL="https://minecraft.curseforge.com/projects/contenttweaker"
logoFile= "contenttweaker_logo.png"
authors="Jaredlll08, kindlich, Skysom and StanH"
description="Customize your Minecraft experience with new blocks and items!"
[[dependencies.contenttweaker]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.contenttweaker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.contenttweaker]]
    modId="crafttweaker"
    mandatory=true
    versionRange="[9.1.94,)"
    ordering="BEFORE"
    side="BOTH"
