modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/CraftTweaker/CraftTweaker/issues"
[[mods]]
modId="contenttweaker"
version="${file.jarVersion}"
displayName="ContentTweaker"
displayURL="https://minecraft.curseforge.com/projects/contenttweaker"
logoFile="logo.png"
authors="Jaredlll08, kindlich, Skysom and StanH"
description="Customize your minecraft experience!"
[[dependencies.contenttweaker]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.contenttweaker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.contenttweaker]]
    modId="crafttweaker"
    mandatory=true
    versionRange="[6,)"
    ordering="BEFORE"
    side="BOTH"